name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Adjust as needed

      - name: Install dependencies
        run: |
          pip install telebot 
    
          pip install -r config/requirements.txt # Adjust path if necessary

      - name: Run bot script
        run: python m.py
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }} # Securely use API key
