name: Run Bot Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the workflow daily at midnight UTC. Adjust as needed.
  workflow_dispatch: # Allows manual triggering

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Run the bot script
      run: python run_bot.py
